spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweater
    username: postgres
    password: hy6ac54wisks777
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
